Twitter zk certificate
Galactica-corp/galactica-monorepo pull request #42
Opened 2024-03-04 10:30 UTC by anhdungle93

PR to add twitterZkCertificate circuits
- Generalize zkCertificateRegistry
- Add scripts, circuits, circuit tests for twitterZkCertificate (similar to the ones for zkKYC)

2024-03-05 17:15 UTC, zwilling requested changes
Can you please check the reasons for the pipeline failing? Something in `yarn build`.
Also, have you ran `yarn lint:fix` to fix the formatting?

2024-03-06 03:12 UTC, anhdungle93 commented on packages/zk-certificates/circuits/twitterZkCertificate.circom
> +    signal input currentTime;
empty line added

2024-03-06 03:12 UTC, anhdungle93 commented on packages/zk-certificates/circuits/twitterZkCertificate.circom
> +    signal output userPubKey[2]; // becomes public as part of the output to check that it corresponds to user address
I also thought so, but wasn't sure.

2024-03-06 04:14 UTC, anhdungle93 commented on packages/zk-certificates/contracts/GuardianRegistry.sol
> +    constructor(string memory _description) Ownable(msg.sender) {
changed that and in some other scripts as well

2024-03-06 04:15 UTC, anhdungle93 commented on packages/galactica-types/src/zkCertStandard.ts
> +  expirationTime: string;
I think we can, if zkCertificate is meant to last forever we can put it as the max int of circom.

2024-04-22 09:43 UTC, zwilling commented on packages/galactica-types/src/zkCertStandard.ts
> +  expirationTime: string;
Changed it in the other branch.

2024-05-03 07:35 UTC, merged